MODULE_MAPPING = {
    "Designer": ['Designer', 'designer'],
    "Feuille de temps (espace de travail natif)": ['(espace de travail natif)', 'Feuille de temps (espace de travail natif)', 'de temps (espace de travail natif)', 'de travail natif)', 'feuille de temps (espace de travail natif)', 'natif)', 'temps (espace de travail natif)', 'travail natif)'],
    "Modifications d’objets/de champs": ['Modifications d’objets/de champs', 'champs', 'd’objets/de champs', 'modifications d’objets/de champs'],
    "Version": ['Version', 'version'],
    "Visualisation des données": ['Visualisation des données', 'des données', 'données', 'visualisation des données'],
    "Api héritée": ['Api héritée', 'api héritée', 'héritée'],
    "Barre d’application": ['Barre d’application', 'barre d’application', 'd’application'],
    "Commandes": ['Commandes', 'commandes'],
    "Localisation": ['Localisation', 'localisation'],
    "Performance": ['Performance', 'performance'],
    "Tâches planifiées": ['Tâches planifiées', 'planifiées', 'tâches planifiées'],
    "Centre des projets": ['Centre des projets', 'centre des projets', 'des projets', 'projets'],
    "Agile": ['Agile', 'agile'],
    "Budget/finances": ['Budget/finances', 'budget/finances'],
    "Éléments de travail": ['de travail', 'travail', 'Éléments de travail', 'éléments de travail'],
    "Espace personnel": ['Espace personnel', 'espace personnel', 'personnel'],
    "Général": ['Général', 'général'],
    "Gestion de projets": ['Gestion de projets', 'de projets', 'gestion de projets', 'projets'],
    "Connecteur de données": ['Connecteur de données', 'connecteur de données', 'de données', 'données'],
    "Talend": ['Talend', 'talend'],
    "Admin o3": ['Admin o3', 'admin o3', 'o3'],
    "Gridboard": ['Gridboard', 'gridboard'],
    "Intégration arm": ['Intégration arm', 'arm', 'intégration arm'],
    "Api plan": ['Api plan', 'api plan', 'plan'],
    "Serveurs": ['Serveurs', 'serveurs'],
    "Client html5": ['Client html5', 'client html5', 'html5'],
    "Designer sciforma": ['Designer sciforma', 'designer sciforma', 'sciforma'],
    "Api rest": ['Api rest', 'api rest', 'rest'],
    "Application mobile feuilles de temps": ['Application mobile feuilles de temps', 'application mobile feuilles de temps', 'de temps', 'feuilles de temps', 'mobile feuilles de temps', 'temps'],
    "Plateforme vantage": ['Plateforme vantage', 'plateforme vantage', 'vantage'],
    "Sciforma": ['Sciforma', 'sciforma'],
    "Vantage": ['Vantage', 'vantage'],
    "Versions": ['Versions', 'versions'],
    "Notices produit": ['Notices produit', 'notices produit', 'produit'],
    "Support": ['Support', 'support'],
    "Formations": ['Formations', 'formations'],
    "Build": ['Build', 'build'],
    "Developer documentation": ['Developer documentation', 'developer documentation', 'documentation'],
    "Feature presentation": ['Feature presentation', 'feature presentation', 'presentation'],
    "Notices": ['Notices', 'notices'],
}
